name: pdr_learning_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # ----------------------------
  # üî• –õ–û–ö–ê–õ–¨–ù–Ü –î–ê–ù–Ü
  # ----------------------------
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.0+4
  path_provider: ^2.1.2

  # –Ü—Å—Ç–æ—Ä—ñ—è —Ç–µ—Å—Ç—ñ–≤
  shared_preferences: ^2.2.2

  # –§–æ—Ä–º–∞—Ç—É–≤–∞–Ω–Ω—è –¥–∞—Ç
  intl: ^0.19.0

  # –ü—Ä–æ—Ñ—ñ–ª—å –∫–æ—Ä–∏—Å—Ç—É–≤–∞—á–∞ (Hive)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

  # –ì–µ–Ω–µ—Ä–∞—Ü—ñ—è –º–æ–¥–µ–ª–µ–π Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/        # GIF, PNG –¥–ª—è –ê–π—Ä–∏
    - assets/pdr/
    - assets/pdr/signs/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
